Ecommerce website/Models/Cart.cs
namespace Ecommerce_website.Models
{
    public class Cart
    {

        public int Id { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

Ecommerce website/Models/Product.cs
namespace Ecommerce_website.Models
{
    public class Product
    {

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string ProductImage { get; set; }

    }
}

Ecommerce website/Pages/Cart.cshtml.cs
using Ecommerce_website.Helpers;
using Ecommerce_website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ecommerce_website.Pages
{
    public class CartModel : PageModel
    {
        public readonly AppDataContext _db;


        public CartModel(AppDataContext db)
        {
            _db = db;
        }
        public List<Cart> cart { get; set; }
        public decimal Total { get; set; }

        [BindProperty (SupportsGet = true)]

        public int id { get; set; }
        public void OnGet()
        {
            if (SessionHelper.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart") != null)
            {
                cart = SessionHelper.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart");
                Total = cart.Sum(i => i.Product.Price * i.Quantity);
            }
            else
            {
                cart = new List<Cart>();
                

               // SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", null);
            }

            
            

        }

        public IActionResult OnGetBuyNow(int id)
        {
            //var productModel = new ProductModel();
            cart = SessionHelper.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<Cart>();
                cart.Add(new Cart
                {
                    Product = _db.Products.Find(id),
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                int index = Exists(cart, id);
                if (index == -1)
                {
                    cart.Add(new Cart
                    {
                        Product = _db.Products.Find(id),
                        Quantity = 1
                    });
                }
                else
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("Cart");
        }

        public IActionResult OnGetDelete(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Cart");
        }

        public IActionResult OnPostUpdate(int[] quantities)
        {
            if (cart != SessionHelper.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart"))
            {
                cart = SessionHelper.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart");
                for (var i = 0; i < cart.Count; i++)
                {
                    cart[i].Quantity = quantities[i];
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                cart = SessionHelper.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart");
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
                return RedirectToPage("Cart");
            
        }

        private int Exists(List<Cart> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

Ecommerce website/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Ecommerce_website.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Ecommerce website/Pages/Form.cshtml.cs
using Ecommerce_website.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace Ecommerce_website.Pages
{



    public class FormModel : PageModel
    {
        
       
        [BindProperty]
        public Product Products { get; set; }

        public readonly AppDataContext _db;

        public FormModel(AppDataContext db)
        {
            _db = db;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        public void OnGet()
        {
            Products = _db.Products.Find(Id);


        }
        public IActionResult OnPost()
        {

            _db.Products.Add(Products);
            _db.SaveChanges();
            return RedirectToPage("/Products");
        }
        
     
        public IActionResult OnPostUpdate()
        {
            _db.Products.Update(Products);
            _db.SaveChanges();
            return RedirectToPage("/Form");
        }
    }
}

Ecommerce website/Pages/Index.cshtml.cs
using Ecommerce_website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ecommerce_website.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public List<Product> products { get; set; }

      
      
        public void OnGet()
        {
            products = new List<Product>{
new Product()
{
Id = 01,
Name = "Barcelona traning kit",

ProductImage = "image/barca.jpeg",
Price= 50
},
new Product()
{
Id = 02,
Name = "Down jacket",

ProductImage = "image/down.jpeg",
Price= 50
},
new Product()
{
Id = 02,
Name = "Padded lightweight gilet",

ProductImage = "image/halfies.jpeg",
Price= 50
}
,
new Product()
{
Id = 02,
Name = "Blue jens",

ProductImage = "image/jeans.jpeg",
Price= 50
}

};
        }
        }
    }

Ecommerce website/Pages/ManageUsers.cshtml.cs
using Ecommerce_website.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce_website.Pages
{
    public class ManageUsersModel : PageModel
    {
        private readonly UserManager<AppUser> UserManager1;

        public List  <AppUser> Users { get; set; }
        public ManageUsersModel(UserManager<AppUser> UserManager) {
            UserManager1 = UserManager;
        }
        public void OnGet() {
            Users = UserManager1.Users.ToList();
        }
        [BindProperty (SupportsGet = true)]
        public string Id { get; set; }   
        public async Task<IActionResult> OnGetDeleteAsync() {
            var users = await UserManager1.FindByIdAsync(Id);
            var Result = await UserManager1.DeleteAsync(users);
            return RedirectToPage("/ManageUsers");
        }
        
        }
    }


Ecommerce website/Pages/Products.cshtml.cs
using Ecommerce_website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Linq;

namespace Ecommerce_website.Pages
{
    public class ProductsModel : PageModel
    {
      
        public readonly AppDataContext _db;

        
        public ProductsModel(AppDataContext db)
        {
            _db = db;
        }
        [BindProperty]
        public string search { get; set; }
        public IEnumerable<Product> products { get; set; }
        
        public Cart Shopping_cart { get; set; }
        public string Email { get; set; }
        [BindProperty (SupportsGet = true)]
        public int Id { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Name { get; set; }

        public void OnGet()
        {
            products = _db.Products.ToList();
            

        }
   
        
        public IActionResult OnGetUpdate()
        {

            _db.Remove(_db.Products.Find(Id));
            _db.SaveChanges();
            return RedirectToPage("/Products");
        }
        public IActionResult OnGetDelete()
        {

            _db.Remove(_db.Products.Find(Id));
            _db.SaveChanges();
            return RedirectToPage("/Products");
        }
        public void OnPost() { 
            products = _db.Products.Where(o => o.Name.Contains(search));
        }
    }


}

Ecommerce website/Pages/aboutus.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ecommerce_website.Pages
{
    public class aboutusModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Ecommerce website/Pages/productthumbnail.cshtml.cs
using Ecommerce_website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ecommerce_website.Pages
{
    public class productthumbnailModel : PageModel
    {
        [BindProperty]
        public Product Products { get; set; }

        public readonly AppDataContext _db;

        public productthumbnailModel(AppDataContext db)
        {
            _db = db;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        public void OnGet()
        {
            Products = _db.Products.Find(Id);


        }
    }
}

Ecommerce website/Pages/Cart.cshtml
@page
@model Ecommerce_website.Pages.CartModel
@{
}


    <form class = "items" method="post" asp-page="cart" asp-page-handler="update">
        <h1 class = "itemheader">Item</h1>
        <h1 class = "quantityheader">Quantity</h1>
        <h1 class = "priceheader">Price</h1>
     @foreach (var item in Model.cart){
                    <section class="rows">
                          
                     <img class = "cart-item-image" src="@item.Product.ProductImage"  />
                     <h1 >@item.Product.Name</h1> 
                     <a>
                    <input class= "cart-quantity-input "type="number" name="quantities" value="@item.Quantity" min="1" style="width: 50px;" /></a>
                    <p class = "price" >£@(item.Product.Price * item.Quantity)</p>
                    <a class="btn btn-danger deletebtn"  asp-page = "cart" asp-route-id="@item.Product.Id" asp-page-handler = "Delete" >Delete</a>
     </section>
     
     }
     
           
      <input class = "btn btn-danger update" type="submit" value="Update" />

</form>
<section class="cart-total">
                <p class="cart-total-title">Total: </p>
                <span class="cart-total-price">£@(
                    
                    
                    Model.Total)</span>
                    
            </section>

Ecommerce website/Pages/Form.cshtml
@page
@model Ecommerce_website.Pages.FormModel
@{
}

<form method="post"  class="form" asp-page="Form">
     <h1>Add product information</h1>
    <div class = "forms">
  <label  class = "label" asp-for= "@Model.Products.Id" ></label>
<input type="text" asp-for="@Model.Products.Id"  class = "input" readonly/>
</div>
<div class = "forms">
<label  class = "label" asp-for="@Model.Products.Name" ></label>
<input class = "input" type="text" asp-for="@Model.Products.Name" />
</div>
<div class = "forms">
<label  class = "label" asp-for="@Model.Products.Description" ></label>
<input  class = "input" type="text" asp-for="@Model.Products.Description" />

</div>
<div class = "forms">
<label  class = "label" asp-for="@Model.Products.Price" ></label>
<input  class = "input" type="text" asp-for="@Model.Products.Price" />
</div>
<div class = "forms">
<label  class = "label" asp-for="@Model.Products.ProductImage" ></label>
<input  class = "input" type="text" asp-for="@Model.Products.ProductImage" />
</div>
<input class = "save" type="submit" value="Save" asp-page-handler = "Update" />
</form>
 
         

Ecommerce website/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="welcome">
    <img class = "image1"src = "/image/cartoon.png"/>
   
    <h1 class="display">Mens clothing</h1>
        <p > Welcome to JOES where you can find fashionable  <br>clothing for men. 
        </p>
        <a asp-page= "Products" class = "shopnow" >Shop now <i class="fa fa-chevron-right" ></i></a>
    
    
</div>

<div class = "product_  products" id="products">
    <p class = "Feature">Featured Products</p>
     @foreach  (var product in Model.products){         
                <div class=" featuredcards allproducts ">
                    <img src="@product.ProductImage"  alt="">
                    
                    <h1 >@product.Name</h1>
                    <p >£@product.Price</p>
                   
                </div>
     }
</div>
<section class= "newsletter">
            <section class="content">
            <section class="contents">
                <h1>Join our newsletter</h1>
                <p>Subscribe to our newsletter to receive the latest updates</p>
            
            <section class="form_S">
                <a href=" " class="Email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                <input class = "e-box" type="Email" name="" value="" placeholder="Enter Email Address">
                <button class="subscribe">Subscribe Now</button>
            </section>
            </section>
            </section>
            </section>

Ecommerce website/Pages/ManageUsers.cshtml
@page
@model Ecommerce_website.Pages.ManageUsersModel
@{

}
<div class = "Users" id="products">
    <h1 class = "header">All accounts</h1>
    <p >Email address</p>
    <p class = "user">Username</p>
     @foreach  (var product in Model.Users){         
                <div class=" allUsers ">
                    
                    
                   
                    <h1 >@product.UserName</h1>
                    <h2 class = "name" >@product.FirstName @product.LastName</h2>
                    <a class = "btn btn-danger deletebtn delete" asp-page = "ManageUsers" asp-route-id="@product.Id" asp-page-handler = "Delete" >Delete</a>
                   
                </div>
     }
</div>

Ecommerce website/Pages/Products.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using Ecommerce_website.Models

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager


@model ProductsModel
@{
    
} <p class = "prod">All products</p>
<form class= "search" method = "post">
    <label asp-for = "search"></label>
    <input asp-for = "search" />
    <input type = "submit" value = "search"/>

</form>
<div class = "products" id="products">
     @foreach  (var product in Model.products){         
                <div class=" allproducts " >
                    <a asp-page="productthumbnail" asp-page-handler="add" asp-route-id="@product.Id"><img src="@product.ProductImage"  alt=""></a>
         
             

            @if (SignInManager.IsSignedIn(User))
            {
                <a class="btn btn-danger buttons button "  asp-page = "Products" asp-route-id="@product.Id" asp-page-handler = "Delete" >Delete</a>
                <a asp-route-id="@product.Id" asp-page = "Form" asp-page-handler = "Update" class="btn btn-danger update button1 button ">Update</a>
            }

                    <a class = "tag"asp-page="productthumbnail" asp-page-handler="add" asp-route-id="@product.Id">@product.Name</a>
                    <p >£@product.Price</p>
                   
                </div>
     }
</div>





Ecommerce website/Pages/aboutus.cshtml
@page
@model Ecommerce_website.Pages.aboutusModel
@{
}
<section class="whole">
        <section class="aboutus">

<h1>About Us </h1>
<p>Welcome to Jeuri of EA, your number one source for mens clothing. We're dedicated to giving you the very best of mens clothing, <br> a focus on
customer satisfaction. Founded in 1999 by Ahmed Abdiqadir,it has come a long way from its beginning. When Ahmed first
started out, his passion for making clothes shopping easier drove him to start the the clothing store and gave him the impetus to turn hard work and inspiration
into to a booming online store. We now serve customers all over the world, 
 and are thrilled to be a part of the eco-friendly wing of the fashion industry.

        
        </section>
        
        <section class=" aboutus1">
            <img src="image/IMG_9917.jpg"  alt="">
            <h2 >Ahmed Abdiqadir</h2>
            <p >Founder</p>
       
            </section>
           
        <section class="contact ">
            <p><i class ="fa fa-phone" ></i><a class= "details">+435654238123</a></p>
            <p><i class ="fa fa fa-envelope" ></i><a class= "details">ahmedowabdiqadir@gmail.com</a></</p>
           
       
            </section>
        </section>

Ecommerce website/Pages/productthumbnail.cshtml
@page
@model Ecommerce_website.Pages.productthumbnailModel
@{
}

<section class="thumnail-content">
            <section class="thumnail-btn" ><img class = "thumnail-img"src="@Model.Products.ProductImage" >
           </section>

<section class="infos">
    <p class="head">@Model.Products.Name</p>
    
    <button class="colours blue"></button>
    <button class = "colours black"></button>
    <button class = "colours grey"></button>
    <section class = "sizecloth">
        <p>Sizes available:</p>
    <button class = "sizes ">XS</button>
    <button class = "sizes sizex">S</button>
    <button class = "sizes sizex">M</button>
    <button class = "sizes sizex">L</button>
    <button class = "sizes sizex">XL</button>
    </section>
    
        <a class = "cart1" asp-page="cart" asp-page-handler="buynow" asp-route-id="@Model.Products.Id">Buy Now</a>
       
    

</section>
</section>